version: "3"
services:
  web:
    build: .
    command: foreman start -f Procfile.dev
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - .:/account-bundler
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: accountbundler
    ports:
      - "23306:3306"
    command:
      [
        --innodb_large_prefix=true,
        --innodb_file_format=barracuda,
        --innodb_file_format_max=barracuda,
        --innodb_file_per_table=true,
        --character-set-server=utf8mb4,
        --explicit_defaults_for_timestamp=true,
      ]
    volumes:
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      - ./db/mysql_data:/var/lib/mysql
